"""Initial books table

Revision ID: f361fecc7044
Revises: 
Create Date: 2025-06-11 13:39:33.065583

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f361fecc7044'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Halls')
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('genre',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('duration',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('genre',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False,
               autoincrement=True)

    op.create_table('Halls',
    sa.Column('Number', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Capacity', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Type', mysql.VARCHAR(length=100), nullable=True),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
